// <auto-generated />
using System;
using InternetForum.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InternetForum.DAL.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20250212162834_NLP")]
    partial class NLP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CommentText = "My last summer holidays was the best",
                            CreatedAt = new DateTime(2025, 2, 12, 17, 28, 33, 754, DateTimeKind.Local).AddTicks(845),
                            PostId = "1",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "2",
                            CommentText = "My last winter holidays was the best",
                            CreatedAt = new DateTime(2025, 5, 14, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(1627),
                            PostId = "2",
                            UserId = "2"
                        },
                        new
                        {
                            Id = "3",
                            CommentText = "My last autumn holidays was the best",
                            CreatedAt = new DateTime(2025, 8, 12, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(1666),
                            PostId = "3",
                            UserId = "3"
                        },
                        new
                        {
                            Id = "4",
                            CommentId = "1",
                            CommentText = "My last summer holidays was the best too. Thank you!",
                            CreatedAt = new DateTime(2025, 2, 12, 17, 28, 33, 754, DateTimeKind.Local).AddTicks(1673),
                            PostId = "1",
                            UserId = "5"
                        },
                        new
                        {
                            Id = "5",
                            CommentId = "2",
                            CommentText = "My last winter holidays was the best too. It was good time",
                            CreatedAt = new DateTime(2025, 5, 14, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(1680),
                            PostId = "2",
                            UserId = "4"
                        },
                        new
                        {
                            Id = "6",
                            CommentText = "My last winter holidays was the best too. It was the best time",
                            CreatedAt = new DateTime(2025, 5, 14, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(1687),
                            PostId = "2",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.CommentReaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CommentId = "1",
                            IsLiked = true,
                            ReactedAt = new DateTime(2025, 2, 12, 18, 28, 33, 755, DateTimeKind.Local).AddTicks(2846),
                            UserId = "5"
                        },
                        new
                        {
                            Id = "2",
                            CommentId = "2",
                            IsLiked = true,
                            ReactedAt = new DateTime(2025, 5, 15, 16, 28, 33, 755, DateTimeKind.Local).AddTicks(3170),
                            UserId = "4"
                        },
                        new
                        {
                            Id = "3",
                            CommentId = "3",
                            IsLiked = false,
                            ReactedAt = new DateTime(2025, 8, 12, 16, 28, 33, 755, DateTimeKind.Local).AddTicks(3191),
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Interest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(2025, 2, 12, 16, 28, 33, 753, DateTimeKind.Local).AddTicks(2202),
                            Header = "Summer holidays",
                            Text = "Tell about your best summer holidays",
                            UpdatedAt = new DateTime(2025, 2, 12, 16, 38, 33, 753, DateTimeKind.Local).AddTicks(2644),
                            UserId = "1"
                        },
                        new
                        {
                            Id = "2",
                            CreatedAt = new DateTime(2025, 5, 13, 16, 28, 33, 753, DateTimeKind.Local).AddTicks(4192),
                            Header = "Winter holidays",
                            Text = "Tell about your best winter holidays",
                            UserId = "3"
                        },
                        new
                        {
                            Id = "3",
                            CreatedAt = new DateTime(2025, 8, 11, 16, 28, 33, 753, DateTimeKind.Local).AddTicks(4313),
                            Header = "Autumn holidays",
                            Text = "Tell about your best Autumn holidays",
                            UserId = "5"
                        },
                        new
                        {
                            Id = "4",
                            CreatedAt = new DateTime(2025, 8, 13, 16, 28, 33, 753, DateTimeKind.Local).AddTicks(4324),
                            Header = "Test post for deleting",
                            Text = "Test text",
                            UserId = "4"
                        },
                        new
                        {
                            Id = "5",
                            CreatedAt = new DateTime(2025, 8, 16, 16, 28, 33, 753, DateTimeKind.Local).AddTicks(4334),
                            Header = "Test post for updating",
                            Text = "Test text",
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.PostReaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLiked")
                        .HasColumnType("bit");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            IsLiked = true,
                            PostId = "1",
                            ReactedAt = new DateTime(2025, 2, 12, 17, 28, 33, 754, DateTimeKind.Local).AddTicks(8945),
                            UserId = "1"
                        },
                        new
                        {
                            Id = "2",
                            IsLiked = false,
                            PostId = "1",
                            ReactedAt = new DateTime(2025, 2, 12, 17, 28, 33, 754, DateTimeKind.Local).AddTicks(9294),
                            UserId = "2"
                        },
                        new
                        {
                            Id = "3",
                            IsLiked = true,
                            PostId = "2",
                            ReactedAt = new DateTime(2025, 5, 14, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(9314),
                            UserId = "3"
                        },
                        new
                        {
                            Id = "4",
                            IsLiked = true,
                            PostId = "3",
                            ReactedAt = new DateTime(2025, 8, 12, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(9322),
                            UserId = "3"
                        },
                        new
                        {
                            Id = "5",
                            IsLiked = false,
                            PostId = "3",
                            ReactedAt = new DateTime(2025, 8, 12, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(9328),
                            UserId = "4"
                        },
                        new
                        {
                            Id = "6",
                            IsLiked = true,
                            PostId = "2",
                            ReactedAt = new DateTime(2025, 5, 4, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(9335),
                            UserId = "4"
                        },
                        new
                        {
                            Id = "7",
                            IsLiked = false,
                            PostId = "1",
                            ReactedAt = new DateTime(2025, 2, 12, 17, 28, 33, 754, DateTimeKind.Local).AddTicks(9341),
                            UserId = "5"
                        },
                        new
                        {
                            Id = "8",
                            IsLiked = true,
                            PostId = "1",
                            ReactedAt = new DateTime(2025, 2, 12, 17, 28, 33, 754, DateTimeKind.Local).AddTicks(9347),
                            UserId = "4"
                        },
                        new
                        {
                            Id = "9",
                            IsLiked = false,
                            PostId = "3",
                            ReactedAt = new DateTime(2025, 8, 12, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(9353),
                            UserId = "5"
                        },
                        new
                        {
                            Id = "10",
                            IsLiked = false,
                            PostId = "2",
                            ReactedAt = new DateTime(2025, 5, 14, 16, 28, 33, 754, DateTimeKind.Local).AddTicks(9360),
                            UserId = "2"
                        });
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.PostTopic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MyPropertyPostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MyPropertyTopicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TopicId", "PostId");

                    b.HasIndex("PostId");

                    b.HasIndex("MyPropertyTopicId", "MyPropertyPostId");

                    b.ToTable("PostTopic");
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Avatar = "https://zoloft100.com/wp-content/uploads/2021/10/Top-5-Benefits-of-Being-an-Electrician-UEI-College.jpg",
                            Bio = "Electrical Engineer",
                            BirthDay = new DateTime(1990, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anton",
                            LastName = "Gerashenko",
                            RegisteredAt = new DateTime(2025, 2, 12, 16, 28, 33, 742, DateTimeKind.Local).AddTicks(53),
                            UserName = "anton_1990"
                        },
                        new
                        {
                            Id = "2",
                            Bio = "18 years",
                            FirstName = "Dmitro",
                            RegisteredAt = new DateTime(2025, 2, 12, 16, 28, 33, 751, DateTimeKind.Local).AddTicks(1485),
                            UserName = "dmidro"
                        },
                        new
                        {
                            Id = "3",
                            BirthDay = new DateTime(2000, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredAt = new DateTime(2025, 2, 12, 16, 28, 33, 751, DateTimeKind.Local).AddTicks(1607),
                            UserName = "user1984"
                        },
                        new
                        {
                            Id = "4",
                            Bio = "The best chef in Iceland",
                            FirstName = "bad",
                            RegisteredAt = new DateTime(2025, 2, 12, 16, 28, 33, 751, DateTimeKind.Local).AddTicks(1627),
                            UserName = "Have_A_Nice_Day"
                        },
                        new
                        {
                            Id = "5",
                            BirthDay = new DateTime(1999, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredAt = new DateTime(2025, 2, 12, 16, 28, 33, 751, DateTimeKind.Local).AddTicks(1635),
                            UserName = "mike_2002"
                        },
                        new
                        {
                            Id = "6",
                            BirthDay = new DateTime(2002, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Danil",
                            RegisteredAt = new DateTime(2025, 2, 12, 16, 28, 33, 751, DateTimeKind.Local).AddTicks(1642),
                            UserName = "danil_owner"
                        });
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.UserInterest", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InterestId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterest");
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Comment", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetForum.DAL.DomainModels.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.CommentReaction", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetForum.DAL.DomainModels.User", "User")
                        .WithMany("CommentReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Post", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.PostReaction", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetForum.DAL.DomainModels.User", "User")
                        .WithMany("PostReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.PostTopic", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.Post", "Post")
                        .WithMany("Topics")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InternetForum.DAL.DomainModels.Topic", null)
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetForum.DAL.DomainModels.PostTopic", "MyProperty")
                        .WithMany()
                        .HasForeignKey("MyPropertyTopicId", "MyPropertyPostId");
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.Topic", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("InternetForum.DAL.DomainModels.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InternetForum.DAL.DomainModels.UserInterest", b =>
                {
                    b.HasOne("InternetForum.DAL.DomainModels.Interest", "Interest")
                        .WithMany("Users")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetForum.DAL.DomainModels.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
